# Generated by Django 4.2.7 on 2023-12-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('cpf', models.IntegerField(unique=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('cardholder', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('card_number', models.CharField(max_length=20)),
                ('card_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'reader',
                'managed': False,
            },
        ),
    ]
