# Generated by Django 5.0.2 on 2024-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='card_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='cardholder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
