# Generated by Django 5.0.2 on 2024-02-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ManyToManyField(blank=True, db_column='id_book', to='book.book')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
