# Generated by Django 5.0 on 2023-12-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_book', models.OneToOneField(db_column='id_book', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='book.book')),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
