# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_reader',
            field=models.OneToOneField(db_column='id_reader', on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('id_reader',)},
        ),
    ]
