# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id_admin', models.OneToOneField(db_column='id_admin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adm.admin')),
            ],
            options={
                'db_table': 'submission',
                'managed': False,
            },
        ),
    ]
