# Generated by Django 5.0.2 on 2024-02-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
        ('book', '0002_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id_admin',
            field=models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='adm.admin'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id_book',
            field=models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
