# Generated by Django 5.0 on 2023-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('edition', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('pdf_url', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('pages_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('cover_url', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=25, null=True)),
                ('submission_status', models.BooleanField()),
                ('submission_date', models.DateTimeField()),
                ('submission_reason', models.TextField()),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.IntegerField(unique=True)),
                ('bank_name', models.CharField(max_length=25)),
                ('bank_agency', models.IntegerField()),
                ('number_account', models.IntegerField()),
                ('account_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
    ]
