# Generated by Django 5.0 on 2023-12-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('edition', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('pdf_url', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('pages_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('cover_url', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=25, null=True)),
                ('submission_status', models.BooleanField()),
                ('submission_date', models.DateTimeField()),
                ('submission_reason', models.TextField()),
                ('id_producer', models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='producer.producer')),
            ],
        ),
    ]
