# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_producer',
            field=models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='producer.producer'),
        ),
    ]
