# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('bank_name', models.CharField(max_length=25)),
                ('bank_agency', models.IntegerField()),
                ('number_account', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'producer',
            },
            bases=('user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
