# Generated by Django 5.0.2 on 2024-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='account_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='bank_agency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='number_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
