# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_book', models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.DO_NOTHING, to='book.book')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
