# Generated by Django 5.0.2 on 2024-02-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='id_reader',
            field=models.ForeignKey(db_column='id_reader', on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('id_book', 'id_reader')},
        ),
    ]
